{
   "partidos":[
      {
         "partido":"PP",
         "mediaAutoubicacion":7.09,
         "votantes":2509,
         "nsnc":302
      },
      {
         "partido":"PSOE",
         "mediaAutoubicacion":3.81,
         "votantes":2330,
         "nsnc":260
      },
      {
         "partido":"IU",
         "mediaAutoubicacion":3,
         "votantes":518,
         "nsnc":14
      },
      {
         "partido":"UPyD",
         "mediaAutoubicacion":4.66,
         "votantes":35,
         "nsnc":1
      },
      {
         "partido":"Ciudadanos",
         "mediaAutoubicacion":5.25,
         "votantes":1869,
         "nsnc":160
      },
      {
         "partido":"Podemos",
         "mediaAutoubicacion":3.14,
         "votantes":1751,
         "nsnc":117
      },
      {
         "partido":"Convergència (CDC)",
         "mediaAutoubicacion":4.96,
         "votantes":192,
         "nsnc":16
      },
      {
         "partido":"ERC",
         "mediaAutoubicacion":2.92,
         "votantes":282,
         "nsnc":8
      },
      {
         "partido":"ICV",
         "mediaAutoubicacion":3.33,
         "votantes":57,
         "nsnc":1
      },
      {
         "partido":"Unió",
         "mediaAutoubicacion":4.94,
         "votantes":12,
         "nsnc":1
      },
      {
         "partido":"PNV",
         "mediaAutoubicacion":4.96,
         "votantes":113,
         "nsnc":14
      },
      {
         "partido":"EH Bildu",
         "mediaAutoubicacion":2.49,
         "votantes":125,
         "nsnc":4
      },
      {
         "partido":"Geroa Bai",
         "mediaAutoubicacion":3.13,
         "votantes":14,
         "nsnc":1
      },
      {
         "partido":"UPN",
         "mediaAutoubicacion":6.57,
         "votantes":4,
         "nsnc":0
      },
      {
         "partido":"BNG",
         "mediaAutoubicacion":3.17,
         "votantes":19,
         "nsnc":1
      },
      {
         "partido":"Anova",
         "mediaAutoubicacion":2.12,
         "votantes":5,
         "nsnc":0
      },
      {
         "partido":"CC",
         "mediaAutoubicacion":5.38,
         "votantes":14,
         "nsnc":4
      },
      {
         "partido":"Nueva Canarias",
         "mediaAutoubicacion":4,
         "votantes":4,
         "nsnc":0
      },
      {
         "partido":"Compromís",
         "mediaAutoubicacion":3.05,
         "votantes":52,
         "nsnc":2
      },
      {
         "partido":"FAC (Foro de Ciudadanos)",
         "mediaAutoubicacion":4.5,
         "votantes":2,
         "nsnc":0
      },
      {
         "partido":"PAR (Partido Aragonés)",
         "mediaAutoubicacion":5.81,
         "votantes":4,
         "nsnc":0
      },
      {
         "partido":"CHA",
         "mediaAutoubicacion":3,
         "votantes":1,
         "nsnc":1
      },
      {
         "partido":"PSM-Entesa/MES",
         "mediaAutoubicacion":3.33,
         "votantes":6,
         "nsnc":0
      },
      {
         "partido":"PI (Proposta per les Illes)",
         "mediaAutoubicacion":4.5,
         "votantes":2,
         "nsnc":0
      },
      {
         "partido":"VOX",
         "mediaAutoubicacion":7.73,
         "votantes":25,
         "nsnc":0
      },
      {
         "partido":"PACMA",
         "mediaAutoubicacion":4,
         "votantes":30,
         "nsnc":11
      },
      {
         "partido":"Los Verdes",
         "mediaAutoubicacion":3.75,
         "votantes":15,
         "nsnc":8
      },
      {
         "partido":"Partido Pirata",
         "mediaAutoubicacion":3.13,
         "votantes":1,
         "nsnc":0
      },
      {
         "partido":"Escaños en Blanco",
         "mediaAutoubicacion":3.6,
         "votantes":4,
         "nsnc":1
      },
      {
         "partido":"España 2000",
         "mediaAutoubicacion":5,
         "votantes":2,
         "nsnc":0
      },
      {
         "partido":"Ahora en Común",
         "mediaAutoubicacion":2,
         "votantes":6,
         "nsnc":0
      },
      {
         "partido":"(En Cataluña) En Comú Podem/Podem en Comú",
         "mediaAutoubicacion":5,
         "votantes":0,
         "nsnc":0
      },
      {
         "partido":"Unidad Popular",
         "mediaAutoubicacion":3.48,
         "votantes":2,
         "nsnc":0
      },
      {
         "partido":"(En Galicia) En Marea",
         "mediaAutoubicacion":2.49,
         "votantes":4,
         "nsnc":0
      },
      {
         "partido":"Partido Cannabis",
         "mediaAutoubicacion":1.81,
         "votantes":3,
         "nsnc":2
      },
      {
         "partido":"Falange Española",
         "mediaAutoubicacion":9.04,
         "votantes":3,
         "nsnc":0
      },
      {
         "partido":"Democracia Nacional",
         "mediaAutoubicacion":10,
         "votantes":0,
         "nsnc":0
      },
      {
         "partido":"SAIn (Partido Solidaridad y Autogestión Internacionalista)",
         "mediaAutoubicacion":5,
         "votantes":1,
         "nsnc":0
      },
      {
         "partido":"Otro",
         "mediaAutoubicacion":3.07,
         "votantes":108,
         "nsnc":5
      },
      {
         "partido":"Voto nulo",
         "mediaAutoubicacion":4.3,
         "votantes":87,
         "nsnc":20
      },
      {
         "partido":"En blanco",
         "mediaAutoubicacion":4.66,
         "votantes":373,
         "nsnc":116
      },
      {
         "partido":"No votaría",
         "mediaAutoubicacion":4.62,
         "votantes":760,
         "nsnc":638
      },
      {
         "partido":"No sabe todavía",
         "mediaAutoubicacion":4.59,
         "votantes":2541,
         "nsnc":786
      },
      {
         "partido":"N.C.",
         "mediaAutoubicacion":4.75,
         "votantes":733,
         "nsnc":340
      }
   ],
   "histogramas":{
      "PP":[
         {
            "x":1,
            "y":1
         },
         {
            "x":2,
            "y":3
         },
         {
            "x":3,
            "y":12
         },
         {
            "x":4,
            "y":20
         },
         {
            "x":5,
            "y":347
         },
         {
            "x":6,
            "y":581
         },
         {
            "x":7,
            "y":587
         },
         {
            "x":8,
            "y":517
         },
         {
            "x":9,
            "y":224
         },
         {
            "x":10,
            "y":219
         }
      ],
      "PSOE":[
         {
            "x":1,
            "y":110
         },
         {
            "x":2,
            "y":140
         },
         {
            "x":3,
            "y":675
         },
         {
            "x":4,
            "y":747
         },
         {
            "x":5,
            "y":535
         },
         {
            "x":6,
            "y":80
         },
         {
            "x":7,
            "y":30
         },
         {
            "x":8,
            "y":9
         },
         {
            "x":9,
            "y":2
         },
         {
            "x":10,
            "y":3
         }
      ],
      "IU":[
         {
            "x":1,
            "y":61
         },
         {
            "x":2,
            "y":88
         },
         {
            "x":3,
            "y":223
         },
         {
            "x":4,
            "y":100
         },
         {
            "x":5,
            "y":35
         },
         {
            "x":6,
            "y":5
         },
         {
            "x":7,
            "y":5
         },
         {
            "x":8,
            "y":1
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "UPyD":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":2
         },
         {
            "x":4,
            "y":12
         },
         {
            "x":5,
            "y":18
         },
         {
            "x":6,
            "y":3
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Ciudadanos":[
         {
            "x":1,
            "y":18
         },
         {
            "x":2,
            "y":27
         },
         {
            "x":3,
            "y":140
         },
         {
            "x":4,
            "y":266
         },
         {
            "x":5,
            "y":694
         },
         {
            "x":6,
            "y":427
         },
         {
            "x":7,
            "y":198
         },
         {
            "x":8,
            "y":70
         },
         {
            "x":9,
            "y":15
         },
         {
            "x":10,
            "y":14
         }
      ],
      "Podemos":[
         {
            "x":1,
            "y":247
         },
         {
            "x":2,
            "y":289
         },
         {
            "x":3,
            "y":583
         },
         {
            "x":4,
            "y":322
         },
         {
            "x":5,
            "y":243
         },
         {
            "x":6,
            "y":48
         },
         {
            "x":7,
            "y":9
         },
         {
            "x":8,
            "y":7
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":2
         }
      ],
      "Convergència (CDC)":[
         {
            "x":1,
            "y":2
         },
         {
            "x":2,
            "y":6
         },
         {
            "x":3,
            "y":20
         },
         {
            "x":4,
            "y":32
         },
         {
            "x":5,
            "y":74
         },
         {
            "x":6,
            "y":32
         },
         {
            "x":7,
            "y":17
         },
         {
            "x":8,
            "y":7
         },
         {
            "x":9,
            "y":1
         },
         {
            "x":10,
            "y":1
         }
      ],
      "ERC":[
         {
            "x":1,
            "y":40
         },
         {
            "x":2,
            "y":66
         },
         {
            "x":3,
            "y":106
         },
         {
            "x":4,
            "y":41
         },
         {
            "x":5,
            "y":16
         },
         {
            "x":6,
            "y":10
         },
         {
            "x":7,
            "y":1
         },
         {
            "x":8,
            "y":1
         },
         {
            "x":9,
            "y":2
         },
         {
            "x":10,
            "y":0
         }
      ],
      "ICV":[
         {
            "x":1,
            "y":8
         },
         {
            "x":2,
            "y":13
         },
         {
            "x":3,
            "y":10
         },
         {
            "x":4,
            "y":7
         },
         {
            "x":5,
            "y":17
         },
         {
            "x":6,
            "y":2
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Unió":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":3
         },
         {
            "x":4,
            "y":2
         },
         {
            "x":5,
            "y":1
         },
         {
            "x":6,
            "y":3
         },
         {
            "x":7,
            "y":2
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "PNV":[
         {
            "x":1,
            "y":4
         },
         {
            "x":2,
            "y":1
         },
         {
            "x":3,
            "y":9
         },
         {
            "x":4,
            "y":9
         },
         {
            "x":5,
            "y":63
         },
         {
            "x":6,
            "y":18
         },
         {
            "x":7,
            "y":5
         },
         {
            "x":8,
            "y":3
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":1
         }
      ],
      "EH Bildu":[
         {
            "x":1,
            "y":25
         },
         {
            "x":2,
            "y":40
         },
         {
            "x":3,
            "y":39
         },
         {
            "x":4,
            "y":15
         },
         {
            "x":5,
            "y":5
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Geroa Bai":[
         {
            "x":1,
            "y":1
         },
         {
            "x":2,
            "y":2
         },
         {
            "x":3,
            "y":7
         },
         {
            "x":4,
            "y":2
         },
         {
            "x":5,
            "y":2
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "UPN":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":5,
            "y":1
         },
         {
            "x":6,
            "y":1
         },
         {
            "x":7,
            "y":1
         },
         {
            "x":8,
            "y":1
         },
         {
            "x":9,
            "y":1
         },
         {
            "x":10,
            "y":0
         }
      ],
      "BNG":[
         {
            "x":1,
            "y":2
         },
         {
            "x":2,
            "y":4
         },
         {
            "x":3,
            "y":5
         },
         {
            "x":4,
            "y":2
         },
         {
            "x":5,
            "y":3
         },
         {
            "x":6,
            "y":1
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Anova":[
         {
            "x":1,
            "y":2
         },
         {
            "x":2,
            "y":1
         },
         {
            "x":3,
            "y":1
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":1
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "CC":[
         {
            "x":1,
            "y":1
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":3
         },
         {
            "x":5,
            "y":5
         },
         {
            "x":6,
            "y":1
         },
         {
            "x":7,
            "y":2
         },
         {
            "x":8,
            "y":1
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":1
         }
      ],
      "Nueva Canarias":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":1
         },
         {
            "x":4,
            "y":2
         },
         {
            "x":5,
            "y":1
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Compromís":[
         {
            "x":1,
            "y":4
         },
         {
            "x":2,
            "y":13
         },
         {
            "x":3,
            "y":23
         },
         {
            "x":4,
            "y":6
         },
         {
            "x":5,
            "y":3
         },
         {
            "x":6,
            "y":3
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "FAC (Foro de Ciudadanos)":[
         {
            "x":1,
            "y":1
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":1
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "PAR (Partido Aragonés)":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":2
         },
         {
            "x":6,
            "y":1
         },
         {
            "x":7,
            "y":1
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "CHA":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":1
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "PSM-Entesa/MES":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":4
         },
         {
            "x":4,
            "y":2
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "PI (Proposta per les Illes)":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":5,
            "y":1
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "VOX":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":2
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":2
         },
         {
            "x":7,
            "y":6
         },
         {
            "x":8,
            "y":8
         },
         {
            "x":9,
            "y":4
         },
         {
            "x":10,
            "y":3
         }
      ],
      "PACMA":[
         {
            "x":1,
            "y":1
         },
         {
            "x":2,
            "y":5
         },
         {
            "x":3,
            "y":12
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":5
         },
         {
            "x":6,
            "y":3
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":3
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Los Verdes":[
         {
            "x":1,
            "y":1
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":5
         },
         {
            "x":4,
            "y":3
         },
         {
            "x":5,
            "y":4
         },
         {
            "x":6,
            "y":1
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Partido Pirata":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":1
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Escaños en Blanco":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":2
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":1
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "España 2000":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":2
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Ahora en Común":[
         {
            "x":1,
            "y":3
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":3
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "(En Cataluña) En Comú Podem/Podem en Comú":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Unidad Popular":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":1
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "(En Galicia) En Marea":[
         {
            "x":1,
            "y":1
         },
         {
            "x":2,
            "y":1
         },
         {
            "x":3,
            "y":1
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Partido Cannabis":[
         {
            "x":1,
            "y":2
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":1
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Falange Española":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":2
         },
         {
            "x":10,
            "y":1
         }
      ],
      "Democracia Nacional":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":0
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "SAIn (Partido Solidaridad y Autogestión Internacionalista)":[
         {
            "x":1,
            "y":0
         },
         {
            "x":2,
            "y":0
         },
         {
            "x":3,
            "y":0
         },
         {
            "x":4,
            "y":0
         },
         {
            "x":5,
            "y":1
         },
         {
            "x":6,
            "y":0
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Otro":[
         {
            "x":1,
            "y":26
         },
         {
            "x":2,
            "y":20
         },
         {
            "x":3,
            "y":24
         },
         {
            "x":4,
            "y":8
         },
         {
            "x":5,
            "y":20
         },
         {
            "x":6,
            "y":8
         },
         {
            "x":7,
            "y":0
         },
         {
            "x":8,
            "y":1
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":0
         }
      ],
      "Voto nulo":[
         {
            "x":1,
            "y":2
         },
         {
            "x":2,
            "y":9
         },
         {
            "x":3,
            "y":10
         },
         {
            "x":4,
            "y":24
         },
         {
            "x":5,
            "y":28
         },
         {
            "x":6,
            "y":9
         },
         {
            "x":7,
            "y":3
         },
         {
            "x":8,
            "y":0
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":1
         }
      ],
      "En blanco":[
         {
            "x":1,
            "y":7
         },
         {
            "x":2,
            "y":8
         },
         {
            "x":3,
            "y":48
         },
         {
            "x":4,
            "y":61
         },
         {
            "x":5,
            "y":185
         },
         {
            "x":6,
            "y":48
         },
         {
            "x":7,
            "y":13
         },
         {
            "x":8,
            "y":2
         },
         {
            "x":9,
            "y":0
         },
         {
            "x":10,
            "y":1
         }
      ],
      "No votaría":[
         {
            "x":1,
            "y":37
         },
         {
            "x":2,
            "y":32
         },
         {
            "x":3,
            "y":97
         },
         {
            "x":4,
            "y":99
         },
         {
            "x":5,
            "y":354
         },
         {
            "x":6,
            "y":77
         },
         {
            "x":7,
            "y":33
         },
         {
            "x":8,
            "y":17
         },
         {
            "x":9,
            "y":8
         },
         {
            "x":10,
            "y":5
         }
      ],
      "No sabe todavía":[
         {
            "x":1,
            "y":61
         },
         {
            "x":2,
            "y":94
         },
         {
            "x":3,
            "y":416
         },
         {
            "x":4,
            "y":529
         },
         {
            "x":5,
            "y":929
         },
         {
            "x":6,
            "y":302
         },
         {
            "x":7,
            "y":123
         },
         {
            "x":8,
            "y":56
         },
         {
            "x":9,
            "y":15
         },
         {
            "x":10,
            "y":16
         }
      ],
      "N.C.":[
         {
            "x":1,
            "y":26
         },
         {
            "x":2,
            "y":29
         },
         {
            "x":3,
            "y":115
         },
         {
            "x":4,
            "y":98
         },
         {
            "x":5,
            "y":284
         },
         {
            "x":6,
            "y":91
         },
         {
            "x":7,
            "y":45
         },
         {
            "x":8,
            "y":31
         },
         {
            "x":9,
            "y":7
         },
         {
            "x":10,
            "y":7
         }
      ]
   }
}